//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFormula1_DF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carro()
        {
            this.PilotoCarroes = new HashSet<PilotoCarro>();
        }
    
        public int id { get; set; }
        public string modelo { get; set; }
        public int ano { get; set; }
        public int unidade { get; set; }
        public int id_equipe { get; set; }
    
        public virtual Equipe Equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotoCarro> PilotoCarroes { get; set; }

        public override string ToString()
        {
            return $"Modelo Carro: {modelo} | Id: {id} | Ano: {ano} \n" +
                $"Unidade: {unidade} | Id Equipe: {id_equipe}";
        }
    }
}
